### ISSUE TITLE
Add Trey's podcast

### ISSUE THREAD

**Issue by willingc** [williln/williln.github.io#8]
@williln Your site is a wonderful resource for folks that are learning. Perhaps add @treyhunner's podcast to the list of podcasts. He's such a wonderful and patient teacher. http://www.weeklypython.chat/

**Comment by williln** [comment]
Added in 31732a7. Thanks, @willingc!

**Comment by willingc** [comment]
Thanks @williln ☀️

**Comment by treyhunner** [comment]
🙌 thanks to both of you! 😁
